version: '3.8'


services:
  api-1:
    image: evergreen-stores-api
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api-1
    networks:
      - evergreen-stores-network
    env_file:
      - .env

  api-2:
    image: evergreen-stores-api
    container_name: api-2
    networks:
      - evergreen-stores-network
    env_file:
      - .env
    depends_on:
      - api-1

  redis-master:
    image: redis:7.0-alpine
    container_name: redis-master
    hostname: redis-master
    volumes:
      - evergreen-stores-database:/data/
    networks:
      evergreen-stores-network:
        ipv4_address: 172.20.0.4
    ports:
      - "6379:6379"

  redis-slave-1:
    image: redis:7.0-alpine
    container_name: redis-slave-1
    hostname: redis-slave-1
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - evergreen-stores-database:/data/
    networks:
      evergreen-stores-network:
        ipv4_address: 172.20.0.5

  redis-slave-2:
    image: redis:7.0-alpine
    container_name: redis-slave-2
    hostname: redis-slave-2
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - evergreen-stores-database:/data/
    networks:
      evergreen-stores-network:
        ipv4_address: 172.20.0.6

  redis-sentinel-1:
    image: redis-sentinel
    build: 
      context: database/redis-sentinel
      dockerfile: Dockerfile
    container_name: redis-sentinel-1
    hostname: redis-sentinel-1
    links:
      - redis-master
    networks:
      evergreen-stores-network:
        ipv4_address: 172.20.0.7
 
  redis-sentinel-2:
    image: redis-sentinel
    container_name: redis-sentinel-2
    hostname: redis-sentinel-2
    links:
      - redis-master
    networks:
      evergreen-stores-network:
        ipv4_address: 172.20.0.8
    depends_on:
      - redis-sentinel-1
 
  redis-sentinel-3:
    image: redis-sentinel
    container_name: redis-sentinel-3
    hostname: redis-sentinel-3
    links:
      - redis-master
    networks:
      evergreen-stores-network:
        ipv4_address: 172.20.0.9
    depends_on:
      - redis-sentinel-1


volumes:
  evergreen-stores-database:
    external: true


networks:
  evergreen-stores-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
