global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yaml

remote_read:
  - url: "http://172.20.0.13:9201/read"

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: ['172.20.0.11:9090']
  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: ['172.20.0.12:3000']
  - job_name: nginx
    metrics_path: /metrics
    static_configs:
      - targets: ['172.20.0.4:8080']
  - job_name: api-1
    static_configs:
      - targets: ['172.20.0.2:5000']
  - job_name: api-2
    static_configs:
      - targets: ['172.20.0.3:5001']

  